apiVersion: 1
datasources:
  - name: FederLoom SQLite
    type: frser-sqlite-datasource
    access: proxy
    uid: federloom-sqlite
    jsonData:
      path: /var/lib/federloom/metrics.db
      pathPrefix: "file:"
      attachLimit: 0
    editable: true
