#!/usr/bin/env bash
# Bootstraps FederLoom on the Mailcow production server.
# Usage: ./deploy/mailcow/bootstrap-mailcow.sh
# Requires: rsync installed locally; SSH access configured in .env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ENV_FILE="$SCRIPT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found."
  echo "  cp $SCRIPT_DIR/.env.example $SCRIPT_DIR/.env"
  echo "  # Edit .env with your server's values"
  exit 1
fi
# shellcheck source=.env.example
source "$ENV_FILE"

ssh_run()  { ssh -l "$SSH_USER" -p "$SSH_PORT" "$SERVER" "$@"; }
sudo_run() { ssh -l "$SSH_USER" -p "$SSH_PORT" "$SERVER" sudo "$@"; }

echo "==> [1/6] Registering CrowdSec bouncer on $SERVER"
sudo_run docker exec "$CROWDSEC_CTR" cscli bouncers delete federloom 2>/dev/null || true
RAW=$(sudo_run docker exec "$CROWDSEC_CTR" cscli bouncers add federloom 2>&1 || true)
API_KEY=$(echo "$RAW" | awk '/API key for/{found=1; next} found && /[A-Za-z0-9+\/=]/{gsub(/[[:space:]]/,""); print; exit}')

if [[ -z "$API_KEY" ]]; then
  echo ""
  echo "ERROR: could not extract CrowdSec API key automatically."
  echo "Run manually on the server:"
  echo "  sudo docker exec $CROWDSEC_CTR cscli bouncers add federloom"
  echo "Then set api_key in $REMOTE_DIR/deploy/mailcow/config.local.yaml and restart."
  echo ""
  echo "Continuing without CrowdSec ingest (enabled: false)."
  CROWDSEC_ENABLED="false"
  API_KEY=""
else
  echo "    Bouncer key registered."
  CROWDSEC_ENABLED="true"
fi

echo "==> [2/6] Syncing repo to $SERVER:$REMOTE_DIR"
rsync -az --delete \
  --exclude='.git' --exclude='bin/' --exclude='data/' \
  --exclude='deploy/honeypot/.env' \
  --exclude='deploy/mailcow/.env' \
  --exclude='deploy/wordpress/.env' \
  --exclude='deploy/mailcow/config.local.yaml' \
  --exclude='deploy/wordpress/config.local.yaml' \
  -e "ssh -l $SSH_USER -p $SSH_PORT" \
  "$REPO_ROOT/" \
  "$SSH_USER@$SERVER:$REMOTE_DIR/"

echo "==> [3/6] Pulling federloom image"
sudo_run docker pull ghcr.io/joeru/federloom:latest

echo "==> [4/6] Writing config.local.yaml (contains api_key — never committed)"
sudo_run bash -c "cat > $REMOTE_DIR/deploy/mailcow/config.local.yaml" <<EOF
# FederLoom config for Mailcow production node.
# Generated by bootstrap-mailcow.sh — do not commit (gitignored).
federation_mode: federated
store:
  dir: /var/lib/federloom
enforce:
  backend: ipset
  set_name: federloom
  chains:
    - DOCKER-USER
    - INPUT
  extra_whitelist:
    - ${PUBLIC_IP}
    - ${TAILSCALE_IP}
    - ${MAILCOW_NETWORK}
    - ${DOCKER_BRIDGE}
reputation:
  block_threshold: 75
  unblock_threshold: 60
  half_life: 168h
  decay_interval: 1h
  rules_file: /etc/federloom/rules.yaml
ingest:
  mailcow_logs:
    enabled: true
    postfix_container: ${POSTFIX_CTR}
    dovecot_container: ${DOVECOT_CTR}
    poll_interval: 30s
  spamtrap:
    enabled: false
    log_file: /var/log/federloom-spamtrap.log
    poll_interval: 5s
  crowdsec:
    enabled: ${CROWDSEC_ENABLED}
    lapi_url: "http://127.0.0.1:8080"
    api_key: "${API_KEY}"
    poll_interval: 30s
    enable_decisions: true
    enable_alerts: false
observability:
  prometheus_addr: ":9101"
api:
  addr: ":9102"
  purpose: "mail"
  taxonomy:
    mail:
      - smtp-*
      - imap-*
      - pop3-*
bootstrap_peers:
  - ${BOOTSTRAP_PEER}
EOF

echo "==> [5/6] Starting FederLoom"
sudo_run docker compose \
  -f "$REMOTE_DIR/deploy/mailcow/docker-compose.yml" \
  up -d

echo "==> [6/6] Waiting 10s for federloomd to print peer ID..."
sleep 10

PEER_ID=$(sudo_run docker logs federloom-mailcow 2>/dev/null \
  | grep 'peer ID:' | tail -1 | awk '{print $NF}' || true)

echo ""
if [[ -z "$PEER_ID" ]]; then
  echo "WARNING: could not read peer ID yet."
  echo "  Check: ssh -l $SSH_USER -p $SSH_PORT $SERVER 'sudo docker logs federloom-mailcow 2>&1 | head -30'"
else
  echo "FederLoom running on $SERVER"
  echo "  Peer ID  : $PEER_ID"
  echo "  Multiaddr: /ip4/$PUBLIC_IP/tcp/7700/p2p/$PEER_ID"
  echo ""
  echo "Federating with honeypot: $BOOTSTRAP_PEER"
  echo ""
  echo "NOTE: for full peering (inbound), open port 7700/tcp in NixOS firewall:"
  echo "  networking.firewall.allowedTCPPorts = [ 7700 ];"
fi
