#!/usr/bin/env bash
# Bootstraps SwarmGuard on the Mailcow production server.
# Usage: ./deploy/mailcow/bootstrap-mailcow.sh
# Requires: ssh access to nixos-mailcow as joe (with sudo), rsync installed locally.
set -euo pipefail

SERVER="nixos-mailcow"
SSH_USER="joe"
REMOTE_DIR="/opt/swarmguard"
CROWDSEC_CTR="mailcowdockerized-crowdsec-1"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ssh_run()  { ssh -l "$SSH_USER" "$SERVER" "$@"; }
sudo_run() { ssh -l "$SSH_USER" "$SERVER" sudo "$@"; }

echo "==> [1/6] Registering CrowdSec bouncer on $SERVER"
RAW=$(sudo_run docker exec "$CROWDSEC_CTR" cscli bouncers add swarmguard 2>&1 || true)
# cscli prints the key as the first non-empty line after "API key for '...':"
API_KEY=$(echo "$RAW" | awk '/API key for/{found=1; next} found && /[A-Za-z0-9+\/=]/{gsub(/[[:space:]]/,""); print; exit}')

if [[ -z "$API_KEY" ]]; then
  echo ""
  echo "ERROR: could not extract CrowdSec API key automatically."
  echo "Run manually on the server:"
  echo "  sudo docker exec $CROWDSEC_CTR cscli bouncers add swarmguard"
  echo "Then set api_key in $REMOTE_DIR/deploy/mailcow/config.local.yaml and restart."
  echo ""
  echo "Continuing without CrowdSec ingest (enabled: false)."
  CROWDSEC_ENABLED="false"
  API_KEY=""
else
  echo "    Bouncer key registered."
  CROWDSEC_ENABLED="true"
fi

echo "==> [2/6] Syncing repo to $SERVER:$REMOTE_DIR"
rsync -az --delete \
  --exclude='.git' --exclude='bin/' --exclude='data/' \
  -e "ssh -l $SSH_USER" \
  "$REPO_ROOT/" \
  "$SSH_USER@$SERVER:$REMOTE_DIR/"

echo "==> [3/6] Building swarmguard image on server"
sudo_run docker build -t swarmguard:latest \
  -f "$REMOTE_DIR/deploy/docker/Dockerfile" "$REMOTE_DIR" -q

echo "==> [4/6] Writing config.local.yaml (contains api_key — never committed)"
sudo_run bash -c "cat > $REMOTE_DIR/deploy/mailcow/config.local.yaml" <<EOF
# SwarmGuard config for Mailcow production node.
# This file is generated by bootstrap-mailcow.sh — do not commit (gitignored).
federation_mode: federated
store:
  dir: /var/lib/swarmguard
enforce:
  backend: ipset
  set_name: swarmguard
  chain: INPUT
  extra_whitelist:
    - 135.181.91.151   # this server's public IP
    - 100.120.31.14    # tailscale
    - 172.22.1.0/24    # mailcow Docker network
    - 172.17.0.0/16    # Docker default bridge
reputation:
  block_threshold: 75
  unblock_threshold: 60
  half_life: 168h
  decay_interval: 1h
  rules_file: /etc/swarmguard/rules.yaml
ingest:
  crowdsec:
    enabled: ${CROWDSEC_ENABLED}
    lapi_url: "http://127.0.0.1:8080"
    api_key: "${API_KEY}"
    poll_interval: 30s
    enable_decisions: true
    enable_alerts: true
observability:
  prometheus_addr: ":9101"
api:
  addr: ":9102"
  purpose: "mail"
  taxonomy:
    mail:
      - smtp-*
      - imap-*
      - pop3-*
EOF

echo "==> [5/6] Starting SwarmGuard"
sudo_run docker compose \
  -f "$REMOTE_DIR/deploy/mailcow/docker-compose.yml" \
  up -d --build

echo "==> [6/6] Waiting 10s for swarmd to print peer ID..."
sleep 10

PEER_ID=$(sudo_run docker logs swarmguard-mailcow 2>/dev/null \
  | grep 'peer ID:' | tail -1 | awk '{print $NF}' || true)

echo ""
if [[ -z "$PEER_ID" ]]; then
  echo "WARNING: could not read peer ID yet."
  echo "  Check: ssh -l $SSH_USER $SERVER 'sudo docker logs swarmguard-mailcow 2>&1 | head -30'"
else
  echo "SwarmGuard running on $SERVER"
  echo "  Peer ID  : $PEER_ID"
  echo "  Multiaddr: /ip4/135.181.91.151/tcp/7700/p2p/$PEER_ID"
  echo ""
  echo "Federating with honeypot: /ip4/167.233.115.41/tcp/7700/p2p/12D3KooWBvpzbEBgcFbHrw3kEFjfdFB2AwimGMhMrVGQBHMpZNjD"
  echo ""
  echo "NOTE: for full peering (inbound), open port 7700/tcp in NixOS firewall:"
  echo "  networking.firewall.allowedTCPPorts = [ 7700 ];"
fi
