#!/usr/bin/env bash
# Bootstraps SwarmGuard on the WordPress production server.
# Usage: ./deploy/wordpress/bootstrap-wordpress.sh
# Requires: ssh access to wordpress-nixos as root (port 2222), rsync installed locally.
set -euo pipefail

SERVER="wordpress-nixos"
SSH_PORT="2222"
SSH_USER="root"
REMOTE_DIR="/opt/swarmguard"
CROWDSEC_CTR="crowdsec"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ssh_run()  { ssh -l "$SSH_USER" -p "$SSH_PORT" "$SERVER" "$@"; }

echo "==> [1/6] Registering CrowdSec bouncer on $SERVER"
RAW=$(ssh_run docker exec "$CROWDSEC_CTR" cscli bouncers add swarmguard 2>&1 || true)
# cscli prints the key as the first non-empty line after "API key for '...':"
API_KEY=$(echo "$RAW" | awk '/API key for/{found=1; next} found && /[A-Za-z0-9+\/=]/{gsub(/[[:space:]]/,""); print; exit}')

if [[ -z "$API_KEY" ]]; then
  echo ""
  echo "ERROR: could not extract CrowdSec API key automatically."
  echo "Run manually on the server:"
  echo "  docker exec $CROWDSEC_CTR cscli bouncers add swarmguard"
  echo "Then set api_key in $REMOTE_DIR/deploy/wordpress/config.local.yaml and restart."
  echo ""
  echo "Continuing without CrowdSec ingest (enabled: false)."
  CROWDSEC_ENABLED="false"
  API_KEY=""
else
  echo "    Bouncer key registered."
  CROWDSEC_ENABLED="true"
fi

echo "==> [2/6] Syncing repo to $SERVER:$REMOTE_DIR"
rsync -az --delete \
  --exclude='.git' --exclude='bin/' --exclude='data/' \
  --exclude='deploy/wordpress/config.local.yaml' \
  --exclude='deploy/mailcow/config.local.yaml' \
  -e "ssh -l $SSH_USER -p $SSH_PORT" \
  "$REPO_ROOT/" \
  "$SSH_USER@$SERVER:$REMOTE_DIR/"

echo "==> [3/6] Building swarmguard image on server"
ssh_run docker build -t swarmguard:latest \
  -f "$REMOTE_DIR/deploy/docker/Dockerfile" "$REMOTE_DIR" -q

echo "==> [4/6] Writing config.local.yaml (contains api_key — never committed)"
ssh_run bash -c "cat > $REMOTE_DIR/deploy/wordpress/config.local.yaml" <<EOF
# SwarmGuard config for WordPress production node.
# This file is generated by bootstrap-wordpress.sh — do not commit (gitignored).
federation_mode: federated
store:
  dir: /var/lib/swarmguard
enforce:
  backend: ipset
  set_name: swarmguard
  chain: INPUT
  extra_whitelist:
    - 65.108.62.108    # this server's public IP
    - 172.21.0.0/16    # traefik Docker network (includes CrowdSec at 172.21.0.3)
    - 172.17.0.0/16    # Docker default bridge
reputation:
  block_threshold: 75
  unblock_threshold: 60
  half_life: 168h
  decay_interval: 1h
  rules_file: /etc/swarmguard/rules.yaml
ingest:
  crowdsec:
    enabled: ${CROWDSEC_ENABLED}
    lapi_url: "http://172.21.0.3:8080"
    api_key: "${API_KEY}"
    poll_interval: 30s
    enable_decisions: true
    enable_alerts: true
observability:
  prometheus_addr: ":9101"
  sqlite_path: "metrics.db"
  sqlite_retention: "720h"   # 30 days
api:
  addr: ":9102"
  purpose: "web"
  taxonomy:
    web:
      - http-*
EOF

echo "==> [5/7] Starting SwarmGuard"
ssh_run docker compose \
  -f "$REMOTE_DIR/deploy/wordpress/docker-compose.yml" \
  up -d --build

echo "==> [6/7] Installing effectiveness exporter cron + textfile dir"
ssh_run bash -c "
  mkdir -p /var/lib/node_exporter/textfile
  chmod +x $REMOTE_DIR/deploy/wordpress/swarmguard-exporter.sh
  chmod +x $REMOTE_DIR/deploy/wordpress/effectiveness-report.sh
  (crontab -l 2>/dev/null | grep -v 'swarmguard-exporter'; echo '*/5 * * * * $REMOTE_DIR/deploy/wordpress/swarmguard-exporter.sh >> /var/log/swarmguard-exporter.log 2>&1') | crontab -
"
echo "    Cron installed; textfile dir ready at /var/lib/node_exporter/textfile"
echo "    NOTE: ensure node_exporter has --collector.textfile.directory=/var/lib/node_exporter/textfile/"

echo "==> [7/7] Waiting 10s for swarmd to print peer ID..."
sleep 10

PEER_ID=$(ssh_run docker logs swarmguard-wordpress 2>/dev/null \
  | grep 'peer ID:' | tail -1 | awk '{print $NF}' || true)

echo ""
if [[ -z "$PEER_ID" ]]; then
  echo "WARNING: could not read peer ID yet."
  echo "  Check: ssh -l $SSH_USER -p $SSH_PORT $SERVER 'docker logs swarmguard-wordpress 2>&1 | head -30'"
else
  echo "SwarmGuard running on $SERVER"
  echo "  Peer ID  : $PEER_ID"
  echo "  Multiaddr: /ip4/65.108.62.108/tcp/7700/p2p/$PEER_ID"
  echo ""
  echo "Federating with honeypot: /ip4/167.233.115.41/tcp/7700/p2p/12D3KooWBvpzbEBgcFbHrw3kEFjfdFB2AwimGMhMrVGQBHMpZNjD"
  echo ""
  echo "NOTE: for full peering (inbound), open port 7700/tcp in NixOS firewall:"
  echo "  networking.firewall.allowedTCPPorts = [ 7700 ];"
fi
