#!/usr/bin/env bash
# Bootstraps FederLoom on the WordPress production server.
# Usage: ./deploy/wordpress/bootstrap-wordpress.sh
# Requires: rsync installed locally; SSH access configured in .env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ENV_FILE="$SCRIPT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found."
  echo "  cp $SCRIPT_DIR/.env.example $SCRIPT_DIR/.env"
  echo "  # Edit .env with your server's values"
  exit 1
fi
# shellcheck source=.env.example
source "$ENV_FILE"

ssh_run() { ssh -l "$SSH_USER" -p "$SSH_PORT" "$SERVER" "$@"; }

echo "==> [1/7] Registering CrowdSec bouncer on $SERVER"
ssh_run docker exec "$CROWDSEC_CTR" cscli bouncers delete federloom 2>/dev/null || true
RAW=$(ssh_run docker exec "$CROWDSEC_CTR" cscli bouncers add federloom 2>&1 || true)
API_KEY=$(echo "$RAW" | awk '/API key for/{found=1; next} found && /[A-Za-z0-9+\/=]/{gsub(/[[:space:]]/,""); print; exit}')

if [[ -z "$API_KEY" ]]; then
  echo ""
  echo "ERROR: could not extract CrowdSec API key automatically."
  echo "Run manually on the server:"
  echo "  docker exec $CROWDSEC_CTR cscli bouncers add federloom"
  echo "Then set api_key in $REMOTE_DIR/deploy/wordpress/config.local.yaml and restart."
  echo ""
  echo "Continuing without CrowdSec ingest (enabled: false)."
  CROWDSEC_ENABLED="false"
  API_KEY=""
else
  echo "    Bouncer key registered."
  CROWDSEC_ENABLED="true"
fi

echo "==> [2/7] Syncing repo to $SERVER:$REMOTE_DIR"
rsync -az --delete \
  --exclude='.git' --exclude='bin/' --exclude='data/' \
  --exclude='deploy/honeypot/.env' \
  --exclude='deploy/mailcow/.env' \
  --exclude='deploy/wordpress/.env' \
  --exclude='deploy/mailcow/config.local.yaml' \
  --exclude='deploy/wordpress/config.local.yaml' \
  -e "ssh -l $SSH_USER -p $SSH_PORT" \
  "$REPO_ROOT/" \
  "$SSH_USER@$SERVER:$REMOTE_DIR/"

echo "==> [3/7] Pulling federloom image"
ssh_run docker pull ghcr.io/joeru/federloom:latest

echo "==> [4/7] Writing config.local.yaml (contains api_key — never committed)"
ssh_run bash -c "cat > $REMOTE_DIR/deploy/wordpress/config.local.yaml" <<EOF
# FederLoom config for WordPress production node.
# Generated by bootstrap-wordpress.sh — do not commit (gitignored).
federation_mode: federated
store:
  dir: /var/lib/federloom
enforce:
  backend: ipset
  set_name: federloom
  chains:
    - DOCKER-USER
    - INPUT
  extra_whitelist:
    - ${PUBLIC_IP}
    - ${WP_NETWORK}
    - ${DOCKER_BRIDGE}
reputation:
  block_threshold: 75
  unblock_threshold: 60
  half_life: 168h
  decay_interval: 1h
  rules_file: /etc/federloom/rules.yaml
ingest:
  crowdsec:
    enabled: ${CROWDSEC_ENABLED}
    lapi_url: "http://${CROWDSEC_LAPI_IP}:8080"
    api_key: "${API_KEY}"
    poll_interval: 30s
    enable_decisions: true
    enable_alerts: false
observability:
  prometheus_addr: ":9101"
  sqlite_path: "metrics.db"
  sqlite_retention: "720h"
api:
  addr: ":9102"
  purpose: "web"
  taxonomy:
    web:
      - http-*
bootstrap_peers:
  - ${BOOTSTRAP_PEER}
EOF

echo "==> [5/7] Starting FederLoom"
ssh_run docker compose \
  -f "$REMOTE_DIR/deploy/wordpress/docker-compose.yml" \
  up -d

echo "==> [6/7] Installing effectiveness exporter cron + textfile dir"
ssh_run bash -c "
  mkdir -p /var/lib/node_exporter/textfile
  chmod +x $REMOTE_DIR/deploy/wordpress/federloom-exporter.sh
  chmod +x $REMOTE_DIR/deploy/wordpress/effectiveness-report.sh
  (crontab -l 2>/dev/null | grep -v 'federloom-exporter'; echo '*/5 * * * * $REMOTE_DIR/deploy/wordpress/federloom-exporter.sh >> /var/log/federloom-exporter.log 2>&1') | crontab -
"
echo "    Cron installed; textfile dir ready at /var/lib/node_exporter/textfile"
echo "    NOTE: ensure node_exporter has --collector.textfile.directory=/var/lib/node_exporter/textfile/"

echo "==> [7/7] Waiting 10s for federloomd to print peer ID..."
sleep 10

PEER_ID=$(ssh_run docker logs federloom-wordpress 2>/dev/null \
  | grep 'peer ID:' | tail -1 | awk '{print $NF}' || true)

echo ""
if [[ -z "$PEER_ID" ]]; then
  echo "WARNING: could not read peer ID yet."
  echo "  Check: ssh -l $SSH_USER -p $SSH_PORT $SERVER 'docker logs federloom-wordpress 2>&1 | head -30'"
else
  echo "FederLoom running on $SERVER"
  echo "  Peer ID  : $PEER_ID"
  echo "  Multiaddr: /ip4/$PUBLIC_IP/tcp/7700/p2p/$PEER_ID"
  echo ""
  echo "Federating with honeypot: $BOOTSTRAP_PEER"
  echo ""
  echo "NOTE: for full peering (inbound), open port 7700/tcp in NixOS firewall:"
  echo "  networking.firewall.allowedTCPPorts = [ 7700 ];"
fi
